metrics:
  graphite:
    host: graphite
    port: 3003
    interval: 60
settings:
  database:
    type: mysql
    stored-requests-query: SELECT accountId, reqid, requestData, 'request' as dataType FROM stored_requests WHERE reqid IN (%REQUEST_ID_LIST%) UNION ALL SELECT accountId, impid, impData, 'imp' as dataType FROM stored_imps WHERE impid IN (%IMP_ID_LIST%)
    amp-stored-requests-query: SELECT accountId, reqid, requestData, 'request' as dataType FROM stored_requests WHERE reqid IN (%REQUEST_ID_LIST%)
    stored-responses-query: SELECT resid, responseData FROM stored_responses WHERE resid IN (%RESPONSE_ID_LIST%)
    host: prebid.crvsi8dzereg.us-east-2.rds.amazonaws.com
    password: prebid123
    user: prebid
    port: 3306
    dbname: prebid